const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const { addMethods } = require('../../utils/toResponse');

const ReceiptSchema = new Schema(
  {
    idMeal: { type: String, required: true},
    strMeal: { type: String, default: '', required: true },
    strCategory: { type: String, default: '' },
    strArea: { type: String, default: '' },
    strSource: { type: String, default: '' },
    strInstructions: { type: String, default: '' },
    strForPersons: { type: Number, default: 0 },
    strRequestsCounter: { type: Number, default: 0 },
    strMealThumb: { type: String, default: '' },
    strTags: { type: String, default: '' },
    strYoutube: { type: String, default: '' },
    strIngredient1: String,
    strMeasure1: String,
    strIngredient2: String,
    strMeasure2: String,
    strIngredient3: String,
    strMeasure3: String,
    strIngredient4: String,
    strMeasure4: String,
    strIngredient5: String,
    strMeasure5: String,
    strIngredient6: String,
    strMeasure6: String,
    strIngredient7: String,
    strMeasure7: String,
    strIngredient8: String,
    strMeasure8: String,
    strIngredient9: String,
    strMeasure9: String,
    strIngredient10: String,
    strMeasure10: String,
    strIngredient11: String,
    strMeasure11: String,
    strIngredient12: String,
    strMeasure12: String,
    strIngredient13: String,
    strMeasure13: String,
    strIngredient14: String,
    strMeasure14: String,
    strIngredient15: String,
    strMeasure15: String,
    strIngredient16: String,
    strMeasure16: String,
    strIngredient17: String,
    strMeasure17: String,
    strIngredient18: String,
    strMeasure18: String,
    strIngredient19: String,
    strMeasure19: String,
    strIngredient20: String,
    strMeasure20: String,
    strIngredient21: String,
    strMeasure21: String,
    strIngredient22: String,
    strMeasure22: String,
    strIngredient23: String,
    strMeasure23: String,
    strIngredient24: String,
    strMeasure24: String,
    strIngredient25: String,
    strMeasure25: String,
    strIngredient26: String,
    strMeasure26: String,
    strIngredient27: String,
    strMeasure27: String,
    strIngredient28: String,
    strMeasure28: String,
    strIngredient29: String,
    strMeasure29: String,
    strIngredient30: String,
    strMeasure30: String
  },
  { collection: 'receipts' }
);

addMethods(ReceiptSchema);

module.exports = mongoose.model('Receipt', ReceiptSchema);
